//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Jul 27 17:28:46 CEST 2005
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface sym
{
	/* terminals */
	public static final int PICTURE = 14;

	public static final int TYPEDEFINITION = 4;

	public static final int BOOLEAN_LITERAL = 6;

	public static final int NUMBER = 2;

	public static final int OCCURS = 9;

	public static final int REDEFINES = 13;

	public static final int STRING_LITERAL = 5;

	public static final int THROUGH = 12;

	public static final int EOF = 0;

	public static final int VALUE = 11;

	public static final int DOT = 8;

	public static final int error = 1;

	public static final int COMMA = 7;

	public static final int TIMES = 10;

	public static final int IDENTIFIER = 3;

	public static final int PACKED_DECIMAL = 15;
}
